services:
  ros2_dev:
    build: .
    container_name: ros2_dev
    stdin_open: true
    tty: true
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./turtle_ws:/root/turtle_ws:rw
      - ./ur5_ws:/root/ur5_ws:rw
    working_dir: /root
    command: bash