[metadata]
name = turtlebot_nav_control
version = 0.0.0
description = TurtleBot navigation control nodes
license = Apache-2.0

# [options]
# packages = find:
# install_requires =
#     setuptools
# zip_safe = true

# [options.entry_points]
# console_scripts =
#     simple_planner = turtlebot_nav_control.simple_planner:main
#     simple_follower = turtlebot_nav_control.simple_follower:main

[develop]
script_dir = $base/lib/turtlebot_nav_control

[install]
install_scripts = $base/lib/turtlebot_nav_control
